-- 1. Insert new record using the sequence
INSERT INTO BILLING (BILL_ID, CUSTOMER_ID, STAFF_ID, BILL_DATE)
VALUES (SEQ_BILL_ID.NEXTVAL, 11011, 51011, SYSDATE);

COMMIT;

-- 2. Query the inserted record
SELECT 
    BILL_ID, 
    CUSTOMER_ID, 
    STAFF_ID, 
    TO_CHAR(BILL_DATE, 'DD-Mon-YYYY HH24:MI:SS') AS BILL_TIMESTAMP
FROM BILLING
WHERE BILL_ID = (SELECT MAX(BILL_ID) FROM BILLING);
